kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: {{ .Values.project }}
subjects:
  {{- range .Files.Lines "project/pod-readers.toml" }}
- kind: User
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
